"""added item category

Revision ID: 07a76c9be734
Revises: d6fd344e684d
Create Date: 2023-11-28 10:34:40.979910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a76c9be734'
down_revision = 'd6fd344e684d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_category', sa.String(), nullable=True))
        batch_op.drop_column('item_catagory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_catagory', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('item_category')

    # ### end Alembic commands ###
