"""added item catagory

Revision ID: d6fd344e684d
Revises: 8508c191e7d3
Create Date: 2023-11-28 10:33:59.761693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fd344e684d'
down_revision = '8508c191e7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_catagory', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item_table', schema=None) as batch_op:
        batch_op.drop_column('item_catagory')

    # ### end Alembic commands ###
